### ISSUE TITLE
[Ubuntu] Maybe use OEM Setup for the way to re-add the User once it's reset?

### ISSUE THREAD

**Issue by feren** [gaining/Resetter#28]
OEM Setup seems a bit more fitting when it comes to what the user should see when they restart their computer once they've Reset it, as it provides the User Addition-ing after Reset, and so on, meaning it's easier to then re-sell that laptop to someone else if they reset it because of wanting to give it to someone else, who'd otherwise have no idea what the password of the user is.

I can see an implementation of OEM Setup being really useful, for these reasons, especially when it comes to re-selling, which is probably what people would want to use this program for, and it's also for Linux Mint and Co, too. What do you think @gaining ?

**Comment by gaining** [comment]
What do you mean by oem setup? Vanilla distros  (which most people use) are not tied to any oems and if you want a configurable password, you just need to use the custom reset option which lets you put in your own user and password. Can you clarify?

**Comment by feren** [comment]
@gaining There's an option in LiveCD to go OEM Setup, and that's basically Ubuntu, but with an OEM Setup Experience, which is basically the User Setup, Language, and Region steps of the Ubuntu Installer, but for the user to then do. It'd be nice if such a link into 'oem-setup-prepare' was made by this program, so that the user DOES NOT need to set a user before Wiping, and can, instead, wipe, reboot and give it to another person, and then they can just set it up, and give themselves a user...

**Comment by gaining** [comment]
Okay, I see. It's a generally interesting idea. The feature that you're talking about isn't really an oem setup but the installer system-configuration setup which asks for location, username/password etc. Now, I would definitely need to fork it up to do only some of the specific things that it does which requires a lot of time that I'm not willing to invest. If you find a way to patch it up let me know,  but I'm not going that route because I believe my current method does the job just fine.
Also, if you're selling or giving a user a computer you could tell them what the default password is and tell them that they'll need to change it later. At least that's how my company does it when giving out new computers to employees.
