### ISSUE TITLE
Skip account creating

### ISSUE THREAD

**Issue by mdrost** [gaining/Resetter#34]
*Issue title: Skip account creating

*Linux Distro and version: Ubuntu 17.04

*Version of Resetter: 1.0.3-stable

*Description of Issue
It is unclear why after I don't checked any account to be removed I am forced to create new account. I want only to remove some packages and use my old account. It should be possible to skip that step.

*content of Log file located in /var/log/resetter/resetter.log
not needed

**Comment by gaining** [comment]
I'm thinking of resolving that for the next release tonight or this weekend. It was just there in case users deleted their main account without setting up a new one first so that they wouldn't be locked out of their system. I've had many users contact me via email about this, they were able to get in via the "default" account so they appreciated it.

Your proposal will be implemented next release sometime tonight or the weekend.
