### ISSUE TITLE
Resetter displays blank in ubuntu gnome 16.04

### ISSUE THREAD

**Issue by marioarizaj** [gaining/Resetter#50]
Blank windows

Ubuntu Gnome 16.04

Reseter 2.2.0

I installed reseter and when trying to open it stays blank

The file has no data in it

**Comment by gaining** [comment]
Hey, it took a while before finally realizing what you mean because you erased the template's content. I think the reason why you're experiencing this is because Ubuntu gnome is using Wayland just like 17.10. If you're using Wayland, run
`xhost +si:localuser:root > /dev/null` then `sudo resetter`  it will theoretically reset your system but it will replace your gnome version with unity. Because that's what the manifest for Ubuntu 16.04 is based on.

Next time opening an issue please leave the template content otherwise, the report will be out of context and others having the same issue won't understand what to do even if there's a solution.

**Comment by gaining** [comment]
Hey, it took a while before finally realizing what you mean because you erased the template's content. I think the reason why you're experiencing this is because Ubuntu gnome is using Wayland just like 17.10. If you're using Wayland, run
`xhost +si:localuser:root > /dev/null` then `sudo resetter`  it will theoretically reset your system but it will replace your gnome version with unity. Because that's what the manifest for Ubuntu 16.04 is based on.

Next time opening an issue please leave the template content otherwise, the report will be out of context and others having the same issue won't understand what to do even if there's a solution.

**Comment by lrntct** [comment]
I got a similar issue on Ubuntu 17.10 running Unity (not wayland).
Launching `resetter` will ask for my password, and then display a blank window.
However, launching with `sudo resetter` seems to work fine.

**Comment by gaining** [comment]
Yeah, running with sudo is the only way and the official workaround when having this problem. Ubuntu 17.10+ does not allow gui apps to run as root peacefully.
