### ISSUE TITLE
Resetter does not contain manifest for ubuntu 19.04

### ISSUE THREAD

**Issue by EthanCahill** [gaining/Resetter#79]
*Issue title: 
Resetter does not cotain manifest for Ubuntu 19.04

*Linux Distro and version:
Ubuntu 19.04

*Version of Resetter:
Resetter 3.0.0

*Description of Issue
After installing resetter on ubuntu 19.04, it has been found that resetter does not conatain a manifest for Ubuntu 19.04

*Content of log file located in /var/log/resetter/resetter.log if applicable:
N/A

**Comment by Spleeen** [comment]
Downloaded, installed, manifest alert...
OK I don't care and click on Custom Reset button... wait... wait...wait... for fuck sake WTF ! sudo apt autoremove purge Resetter

**Comment by gaining** [comment]
@Spleeen Maybe see a shrink about that anger first before interacting with people?

**Comment by Spleeen** [comment]
In the meantime, we have an answer from you on the only issue of your software! He has been waiting since July 9 for an answer !

How can a newly installed software be so buggy ? What does he do when he waits endlessly ? Very strange…

**Comment by gaining** [comment]
@Spleeen I don't have time to deal with an entitled self righteous prick with horrible manners. If you want to support Ubuntu 19.04, you can do it yourself, it is an open source project after all. I've laid out the [instructions](https://www.youtube.com/watch?v=k0wsPzO355o) for those who want to do it as @acloserview and few others have done [here](https://github.com/gaining/Resetter/pull/77). This project is a hobby for me, I haven't had the time to update it for new distros and no you're incorrect, it's not a bug because I never claimed that resetter supports ubuntu 19.04 or any other distros that came after it.

If you read the licence of this program under the GPL, I am in no obligation to support your needs. 

> Resetter is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public Licence for more details.

Now go take your self righteousness somewhere else and go see a shrink.

**Comment by gaining** [comment]
Thanks to @kenshin23, this is resolved.
